apiVersion: v1
kind: Template
labels:
  app: ldapexporter
  template: ldapexporter-buildconfig
metadata:
  annotations:
    description: OpenLDAP Exporter - BuildConfig
      see https://github.com/Worteks/docker-ldapexporter
    iconClass: icon-openshift
    openshift.io/display-name: OpenLDAP Exporter
    tags: openldap,ldapexporter
  name: ldapexporter-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds OpenLDAP Exporter images
    labels:
      name: ldapexporter-${FRONTNAME}-${OPENLDAP_EXPORTER_REPOSITORY_REF}
    name: ldapexporter-${FRONTNAME}-${OPENLDAP_EXPORTER_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 400m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${OPENLDAP_EXPORTER_REPOSITORY_URL}
        ref: "${OPENLDAP_EXPORTER_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: ldapexporter-${FRONTNAME}:${OPENLDAP_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: OPENLDAP_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: OPENLDAP_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your OpenLDAP exporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-ldapexporter.git
