apiVersion: v1
kind: Template
labels:
  app: ldapexporter
  template: ldapexporter-imagestream
metadata:
  annotations:
    description: OpenLDAP Exporter - ImageStream
      see https://github.com/Worteks/docker-ldapexporter
    iconClass: icon-openshift
    openshift.io/display-name: OpenLDAP Exporter
    tags: openldap,ldapexporter
  name: ldapexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in OpenLDAP Exporter image
    name: ldapexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
